name: Reminders
description: an application to remember with images.
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  google_nav_bar: ^5.0.6
  sqflite: ^2.3.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  url_launcher: ^6.0.9
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
